services:
  backend:
    image: deer-flow-api
    container_name: deer-flow-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./conf.yaml:/app/conf.yaml
    restart: unless-stopped
    networks:
      - deer-flow-network

  frontend:
    image: deer-flow-web
    container_name: deer-flow-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - deer-flow-network

networks:
  deer-flow-network:
    driver: bridge

